// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Rule {
    "name": string;
    "trigger": string;
    "command": string;
    "parameters": { [_ in string]?: string } | null;
}
