// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * Command is an imperative request. Its Name follows verb.noun ordering.
 */
export interface Command {
    "id": string;
    "type": domain$0.MessageType;
    "name": string;
    "equipmentId": string;
    "correlationId": string;
    "causationId": string;
    "status": Status;
    "createdAt": string;
    "completedAt"?: string | null;
    "parameters": { [_ in string]?: any } | null;
    "error"?: string;
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusPending = "pending",
    StatusSending = "sending",
    StatusSucceeded = "succeeded",
    StatusFailed = "failed",
};
