// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Match {
    "names": string[] | null;
}

export interface Rule {
    "name": string;
    "match": Match;
    "sinks": string[] | null;
}
