// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "./internal/ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as automation$0 from "./internal/automation/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "./internal/device/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as secs$0 from "./internal/driver/secs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as event$0 from "./internal/event/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as router$0 from "./internal/router/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sink$0 from "./internal/sink/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sqlite$0 from "./internal/store/sqlite/models.js";

export interface AIActionPermission {
    "id": string;
    "tool": string;
    "equipmentId": string;
    "command": string;
    "summary": string;
    "risk": string;
    "parameters": { [_ in string]?: any } | null;
    "parameterDiff": { [_ in string]?: ParameterChange } | null;
    "expiresAt": string;
}

export interface AIProfileConfig {
    "id": string;
    "name": string;
    "provider": string;
    "baseURL": string;
    "model": string;
    "apiKey"?: string;
    "hasApiKey": boolean;
    "isDefault": boolean;
}

export interface CopilotReply {
    "answer": string;
    "evidence": string[] | null;
    "suggestions": string[] | null;
    "permission"?: AIActionPermission | null;
    "tools"?: ai$0.ToolResult[] | null;
}

export interface CopilotStreamEvent {
    "requestId": string;
    "sessionId": string;
    "delta"?: string;
    "done": boolean;
    "reply"?: CopilotReply | null;
}

export interface EquipmentConfigComparison {
    "runtimePath": string;
    "packagedCount": number;
    "runtimeCount": number;
    "missing": string[] | null;
    "extra": string[] | null;
    "changed": string[] | null;
}

export interface EquipmentConfigSaveResult {
    "path": string;
    "restartRequired": boolean;
}

export interface EquipmentMergeResult {
    "added": string[] | null;
    "path": string;
    "restartRequired": boolean;
}

export interface ParameterChange {
    "before"?: any;
    "after": any;
}

export interface PermissionPolicy {
    "mode": string;
    "equipment": string[] | null;
    "commands": string[] | null;
    "ttlMinutes": number;
}

export interface ProfileDocument {
    "path": string;
    "yaml": string;
}

export interface ProfilePreview {
    "message": secs$0.Message;
    "events": event$0.Event[] | null;
}

export interface ProfileSaveResult {
    "path": string;
    "reloadedDevices": string[] | null;
}

export interface ProfileSummary {
    "path": string;
    "name": string;
    "vendor": string;
    "model": string;
    "version": string;
    "adapter": string;
    "valid": boolean;
    "error"?: string;
}

export interface ProfileValidation {
    "valid": boolean;
    "error"?: string;
    "summary": ProfileSummary;
    "warnings": string[] | null;
}

export interface RuleReloadResult {
    "routes": number;
    "automations": number;
}

export interface StudioSnapshot {
    "devices": device$0.Snapshot[] | null;
    "routes": router$0.Rule[] | null;
    "deliveries": sink$0.Delivery[] | null;
    "automations": automation$0.Rule[] | null;
    "alarms": sqlite$0.Alarm[] | null;
    "storage": sqlite$0.Stats;
    "generated": string;
}
