// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as automation$0 from "./internal/automation/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "./internal/device/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as router$0 from "./internal/router/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sink$0 from "./internal/sink/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sqlite$0 from "./internal/store/sqlite/models.js";

export interface CopilotReply {
    "answer": string;
    "evidence": string[] | null;
    "suggestions": string[] | null;
}

export interface StudioSnapshot {
    "devices": device$0.Snapshot[] | null;
    "routes": router$0.Rule[] | null;
    "deliveries": sink$0.Delivery[] | null;
    "automations": automation$0.Rule[] | null;
    "alarms": sqlite$0.Alarm[] | null;
    "storage": sqlite$0.Stats;
    "generated": string;
}
