// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AskCopilot is a grounded, deterministic first-pass assistant. A provider-backed
 * implementation can replace it without moving credentials into the frontend.
 */
export function AskCopilot(question: string, equipmentID: string): $CancellablePromise<$models.CopilotReply> {
    return $Call.ByID(1361152184, question, equipmentID);
}

export function ConnectDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(3173062369, id);
}

export function DisconnectDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(4192432587, id);
}

export function EmitSimulatorScenario(id: string, scenario: string): $CancellablePromise<void> {
    return $Call.ByID(3108572356, id, scenario);
}

export function Snapshot(): $CancellablePromise<$models.StudioSnapshot> {
    return $Call.ByID(799204223);
}
