// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "./internal/ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "./internal/device/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sqlite$0 from "./internal/store/sqlite/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AIConfig(): $CancellablePromise<ai$0.Config> {
    return $Call.ByID(1418556419);
}

export function ApplyHistoryRetention(days: number): $CancellablePromise<sqlite$0.RetentionResult> {
    return $Call.ByID(2964914099, days);
}

/**
 * AskCopilot is a grounded, deterministic first-pass assistant. A provider-backed
 * implementation can replace it without moving credentials into the frontend.
 */
export function AskCopilot(question: string, equipmentID: string, attachments: ai$0.Attachment[] | null): $CancellablePromise<$models.CopilotReply> {
    return $Call.ByID(1361152184, question, equipmentID, attachments);
}

/**
 * AskCopilotStream starts a provider-backed streaming request and returns
 * immediately. Deltas and the final reply are emitted through
 * studio:copilot-stream so the Wails call itself never buffers the full answer.
 */
export function AskCopilotStream(requestID: string, question: string, equipmentID: string, attachments: ai$0.Attachment[] | null): $CancellablePromise<void> {
    return $Call.ByID(159554888, requestID, question, equipmentID, attachments);
}

export function ClearCopilotHistory(equipmentID: string): $CancellablePromise<void> {
    return $Call.ByID(3117216080, equipmentID);
}

export function CompareEquipmentConfig(): $CancellablePromise<$models.EquipmentConfigComparison> {
    return $Call.ByID(3856062616);
}

export function ConfigureAI(config: ai$0.Config, apiKey: string): $CancellablePromise<void> {
    return $Call.ByID(3253751891, config, apiKey);
}

export function ConnectDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(3173062369, id);
}

export function CopilotHistory(equipmentID: string): $CancellablePromise<sqlite$0.CopilotMessage[] | null> {
    return $Call.ByID(63581007, equipmentID);
}

export function DisconnectDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(4192432587, id);
}

export function EmitSimulatorScenario(id: string, scenario: string): $CancellablePromise<void> {
    return $Call.ByID(3108572356, id, scenario);
}

export function EquipmentConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(1315334092);
}

export function ListAIProfiles(): $CancellablePromise<$models.AIProfileConfig[] | null> {
    return $Call.ByID(874361723);
}

export function MergePackagedDemoDevices(): $CancellablePromise<$models.EquipmentMergeResult> {
    return $Call.ByID(956824401);
}

export function QueryCommandHistory(query: sqlite$0.HistoryQuery): $CancellablePromise<sqlite$0.CommandPage> {
    return $Call.ByID(2864890778, query);
}

export function QueryEventHistory(query: sqlite$0.HistoryQuery): $CancellablePromise<sqlite$0.EventPage> {
    return $Call.ByID(723671001, query);
}

export function QueryTraceHistory(query: sqlite$0.HistoryQuery): $CancellablePromise<sqlite$0.TracePage> {
    return $Call.ByID(1853524174, query);
}

export function ReloadRules(): $CancellablePromise<$models.RuleReloadResult> {
    return $Call.ByID(3389865889);
}

export function ResolveAIAction(permissionID: string, allow: boolean): $CancellablePromise<$models.CopilotReply> {
    return $Call.ByID(1547149465, permissionID, allow);
}

export function SaveAIProfiles(profiles: $models.AIProfileConfig[] | null, defaultID: string): $CancellablePromise<void> {
    return $Call.ByID(1093772770, profiles, defaultID);
}

export function SaveDeviceOrder(order: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2024686028, order);
}

export function SaveEquipmentConfig(config: device$0.Config): $CancellablePromise<$models.EquipmentConfigSaveResult> {
    return $Call.ByID(73226380, config);
}

export function Snapshot(): $CancellablePromise<$models.StudioSnapshot> {
    return $Call.ByID(799204223);
}

export function TestAIConfiguration(config: ai$0.Config, apiKey: string): $CancellablePromise<string> {
    return $Call.ByID(2294031345, config, apiKey);
}
