// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * Event is the protocol-independent contract consumed by routes and sinks.
 */
export interface Event {
    "id": string;
    "type": domain$0.MessageType;
    "name": string;
    "equipmentId": string;
    "correlationId": string;
    "causationId": string;
    "commandId"?: string;
    "timestamp": string;
    "source": Source;
    "data": { [_ in string]?: any } | null;
}

export interface Source {
    "protocol": string;
    "stream": number;
    "function": number;
    "ceid"?: number;
}
