// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum MessageType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeCommand = "command",
    TypeEvent = "event",
};
