// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Delivery {
    "sink": string;
    "eventId": string;
    "eventName": string;
    "status": string;
    "timestamp": string;
}
