devices:
  - id: ETCHER-01
    badge: "01"
    name: Etcher #1
    profile: profiles/demo/etcher-x100.yaml
    adapter: generic-gem
    driver: simulator
    role: equipment-simulator
    autoConnect: true
    connection:
      protocol: hsms-ss
      mode: passive
      host: 0.0.0.0
      port: 5001
      sessionId: 0
      connectTimeoutSeconds: 10
      replyTimeoutSeconds: 45

  - id: AOI-01
    badge: AOI
    name: AOI Inspection #1
    profile: profiles/demo/aoi-v200.yaml
    adapter: demo-aoi-v200
    driver: simulator
    role: equipment-simulator
    autoConnect: true
    connection:
      protocol: hsms-ss
      mode: passive
      host: 0.0.0.0
      port: 5101
      sessionId: 0
      connectTimeoutSeconds: 10
      replyTimeoutSeconds: 45

  - id: OVEN-01
    badge: OVN
    name: Thermal Oven #1
    profile: profiles/demo/oven-t300.yaml
    adapter: demo-oven-t300
    driver: simulator
    role: equipment-simulator
    autoConnect: true
    connection:
      protocol: hsms-ss
      mode: passive
      host: 0.0.0.0
      port: 5201
      sessionId: 0
      connectTimeoutSeconds: 10
      replyTimeoutSeconds: 45
