// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum ConnectionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateDisconnected = "disconnected",
    StateConnecting = "connecting",
    StateSelected = "selected",
    StateError = "error",
};

export enum Direction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DirectionIn = "IN",
    DirectionOut = "OUT",
};

/**
 * Message is the SDK-neutral representation used outside this package.
 */
export interface Message {
    "id": string;
    "equipmentId": string;
    "direction": Direction;
    "timestamp": string;
    "stream": number;
    "function": number;
    "wait": boolean;
    "systemBytes": number;
    "sml": string;
    "tree": string;
    "rawHex"?: string;
    "ceid"?: number;
    "fields"?: { [_ in string]?: any } | null;
    "reports"?: { [_ in `${number}`]?: any[] | null } | null;
    "ack"?: number | null;
    "metadata"?: { [_ in string]?: string } | null;
}

export interface ProtocolDiagnostics {
    "dataSent": number;
    "dataReceived": number;
    "dataErrors": number;
    "decodeErrors": number;
    "replyMismatches": number;
    "reconnects": number;
    "inflight": number;
    "linktestSent": number;
    "linktestReceived": number;
    "linktestErrors": number;
    "separateReceived": number;
    "rejectSent": number;
    "rejectReceived": number;
}
