// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "../../ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as command$0 from "../../command/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as secs$0 from "../../driver/secs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as event$0 from "../../event/models.js";

export interface Alarm {
    "equipmentId": string;
    "alarmId": string;
    "code": string;
    "text": string;
    "severity": string;
    "state": string;
    "raisedAt": string;
    "clearedAt"?: string | null;
    "correlationId": string;
}

export interface CommandPage {
    "items": command$0.Command[] | null;
    "total": number;
    "page": number;
}

export interface CopilotMessage {
    "id": string;
    "sessionId": string;
    "equipmentId": string;
    "role": string;
    "text": string;
    "attachments": ai$0.Attachment[] | null;
    "evidence": string[] | null;
    "permission"?: CopilotPermission | null;
    "permissionStatus"?: string;
    "createdAt": string;
}

export interface CopilotPermission {
    "id": string;
    "tool": string;
    "equipmentId": string;
    "command": string;
    "summary": string;
    "risk": string;
    "parameters": { [_ in string]?: any } | null;
}

export interface CopilotSession {
    "id": string;
    "title": string;
    "scope": string;
    "createdAt": string;
    "updatedAt": string;
    "messageCount": number;
}

export interface EventPage {
    "items": event$0.Event[] | null;
    "total": number;
    "page": number;
}

export interface HistoryQuery {
    "page": number;
    "pageSize": number;
    "equipmentId": string;
    "search": string;
    "direction": string;
    "name": string;
    "status": string;
    "sinceHours": number;
}

export interface RetentionResult {
    "traceDeleted": number;
    "eventDeleted": number;
    "commandDeleted": number;
    "alarmDeleted": number;
    "copilotDeleted": number;
    "databaseBytes": number;
}

export interface Stats {
    "traceCount": number;
    "eventCount": number;
    "commandCount": number;
    "alarmCount": number;
    "droppedTrace": number;
    "databaseBytes": number;
}

export interface TracePage {
    "items": secs$0.Message[] | null;
    "total": number;
    "page": number;
}
