// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Alarm {
    "equipmentId": string;
    "alarmId": string;
    "code": string;
    "text": string;
    "severity": string;
    "state": string;
    "raisedAt": string;
    "clearedAt"?: string | null;
    "correlationId": string;
}

export interface Stats {
    "traceCount": number;
    "eventCount": number;
    "commandCount": number;
    "alarmCount": number;
    "droppedTrace": number;
}
