// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as command$0 from "../command/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as secs$0 from "../driver/secs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as event$0 from "../event/models.js";

export interface AvailableCommand {
    "name": string;
    "displayName": string;
    "stream": number;
    "function": number;
    "wait": boolean;
    "parameters": string[] | null;
}

export interface Config {
    "devices": Definition[] | null;
}

export interface ConnectionConfig {
    "protocol": string;
    "mode": string;
    "host": string;
    "port": number;
    "sessionId": number;
    "connectTimeoutSeconds": number;
    "replyTimeoutSeconds": number;
}

export interface Definition {
    "id": string;
    "badge": string;
    "name": string;
    "profile": string;
    "adapter": string;
    "driver": string;
    "role": string;
    "autoConnect": boolean;
    "connection": ConnectionConfig;
}

export interface RuntimeDiagnostics {
    "connectAttempts": number;
    "messagesIn": number;
    "messagesOut": number;
    "parseErrors": number;
    "queueDrops": number;
    "commandFailures": number;
    "lastConnectedAt"?: string | null;
    "lastMessageAt"?: string | null;
    "lastError"?: string;
    "protocol": secs$0.ProtocolDiagnostics;
}

export interface SimulatorScenario {
    "id": string;
    "displayName": string;
    "event": string;
    "stream": number;
    "function": number;
}

export interface Snapshot {
    "id": string;
    "badge": string;
    "name": string;
    "profile": string;
    "profileName": string;
    "vendor": string;
    "model": string;
    "driver": string;
    "role": string;
    "adapter": string;
    "autoConnect": boolean;
    "protocol": string;
    "mode": string;
    "host": string;
    "port": number;
    "sessionId": number;
    "connectTimeoutSeconds": number;
    "replyTimeoutSeconds": number;
    "state": secs$0.ConnectionState;
    "stateDetail": string;
    "messages": secs$0.Message[] | null;
    "events": event$0.Event[] | null;
    "commands": command$0.Command[] | null;
    "availableCommands": AvailableCommand[] | null;
    "scenarios": SimulatorScenario[] | null;
    "diagnostics": RuntimeDiagnostics;
}
