// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as command$0 from "../command/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as secs$0 from "../driver/secs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as event$0 from "../event/models.js";

export interface SimulatorScenario {
    "id": string;
    "displayName": string;
    "event": string;
    "direction": string;
    "stream": number;
    "function": number;
}

export interface Snapshot {
    "id": string;
    "name": string;
    "profile": string;
    "profileName": string;
    "vendor": string;
    "model": string;
    "driver": string;
    "host": string;
    "port": number;
    "state": secs$0.ConnectionState;
    "stateDetail": string;
    "messages": secs$0.Message[] | null;
    "events": event$0.Event[] | null;
    "commands": command$0.Command[] | null;
    "scenarios": SimulatorScenario[] | null;
}
