// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Attachment {
    "name": string;
    "mediaType": string;
    "dataURL": string;
    "size": number;
}

export interface Config {
    "provider": string;
    "baseURL": string;
    "model": string;
}

export interface ToolResult {
    "name": string;
    "input": { [_ in string]?: any } | null;
    "result": any;
}
